### ISSUE TITLE
Fission reactor has some usability issues

### ISSUE THREAD

**Issue by thePalindrome** [Silfryi/mechcanical-technology-rocketry#2]
I'd really love to have a guidebook of some kind. If Patchouli is on the table, the multiblock in-world render could help quite a bit! It'd also be nice to help explain the mechanics.

In addition, some way to access the fuel bundle IO while the heat exchanger is in place would be nice (could be done by slimming down the fuel rod connector, not sure how easy that'd be to do in CT)

Lastly, some way to get an idea of the heat in the fuel bundles would be nice!

( If you think everything would be better suited to its own mod, let me know!)

**Comment by voidsong-dragonfly** [comment]
Closed due to new reactor with new mechanics
